exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".pyenv",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".pixi",
]
extend-include = ["*.ipynb"]

indent-width   = 4
line-length    = 100
target-version = "py314"

[lint]

preview = true

fixable = ["ALL"]
ignore = [
    'B006',   # Learn Python yo!
    'COM819', # Trailing commas is da bomb
    'COM812',
    'E731',   # Do not assign to lambda
    'ERA001',
    'T201',   # comment code, prints are lax during development
    'G004',   # Logging format string should not use f-string
    'RET503', # No explicit return None (all the other rules are about removing unnecessary things like this)
    #'RUF012', # Mutable class attributes should be annotated with ClassVar
    'S311',    # Standard pseudo-random generators are not suitable for security/cryptographic purposes
    'SIM108',  # don't like ternary operator
    'SIM300',  # Yoda is wiser than you!
    'TRY003',  # Avoid long messages outside of exception class
    'TRY004',  # Use TypeError instead of ValueError
    'TRY301',  # Abstract raise garbage,
    'F405',    # Undefined or defined from star imports,
    "F403",    # Cannot detect names from star imports (but Pyright can so this doesn't really matter)
    "D418",    # Overload docstrings give contextually relevant information
    "E501",    # Line length is purely stylistic
    "PLC0415", # Sometimes lazy imports are necessary
]

select = [
    'A',     # flake8-builtins
    'ASYNC', # https://docs.astral.sh/ruff/rules/#flake8-async-async
    'B',     # flake8-bugbear
    'BLE',   # flake8-blind-except
    'C4',    # unnecessary comprehensions, map()
    'COM',   # flake8-commas
    'DTZ',   # flake8-datetimez
    'E',     # pycodestyle
    'ERA',   # No commented out code
    'EXE',   # flake8-executable
    'F',     # pyflakes
    'FLY',   # flynt
    'G',     # flake8-logging-format
    'I',     # isort
    'ICN',   # https://github.com/joaopalmeiro/flake8-import-conventions
    'ISC',   # https://pypi.org/project/flake8-implicit-str-concat/
    'LOG',   # flake8-logging
    'PERF',  # perflint
    'PIE',   # https://pypi.org/project/flake8-pie/
    'PLC',   # Pylint conventions
    'PLE',   # Pylint error
    'PLW',   # Pylint warnings
    'PT',    # https://pypi.org/project/flake8-pytest-style/
    'PTH',   # flake8 use pathlib
    'RET',   # https://pypi.org/project/flake8-return/
    'RUF',   # Ruff rules
    'S',     # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    'SIM',   # https://pypi.org/project/flake8-simplify/
    'T',     # flake8-debugger
    "TC",
    'TRY',   # tryceratops
    'UP',    # pyupgrade
    'W',     # pycodestyle
    #'ARG',  # flake8 unused arguments (not really helpful, unused func args are common and ok)
    'D2', # pydocstyle (too much),
    'D4',
    #'N',  # pep8-naming (too opinionated)
    #'NPY', # numpy
    #'PD', # pandas
    #'PL',  # Full Pylint (too much)
    #'PLR',  # Pylint refactor (too much/too opinionated)
]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
future-annotations = true
logger-objects     = ["setup_console.console"]

    [lint.flake8-builtins]
    ignorelist = ['id', 'input']

    [lint.per-file-ignores]
    "**/*.ipynb" = ["ANN", "BLE001", "C401", "D", "F401", "I"]
    "**/*.pyi" = ["D", "N", "A001", "A002"]
    "**/tests/**" = [
        "PLR",
        "ANN001",
        "S101",
        "ANN201",
        "D103",
        "PLC2701",
        "PLC0415",
        "SLF001",
        "FBT001",
        "D102",
        "D101",
        "S106",
        "ARG001",
        "S105",
    ]
    "__init__.py" = ["E402"]

    [lint.flake8-annotations]
    mypy-init-return = false


[format]

preview                   = true
skip-magic-trailing-comma = false

indent-style = "space"
line-ending  = "auto"
quote-style  = "single"

docstring-code-format      = true
docstring-code-line-length = "dynamic"
